editor: source

execute:
  cache: false # "Danger, Will Robinson!"
  freeze: false # If you plan to use it, remember to disable it afterward!

project:
  type: website
  output-dir: docs
  render: [index.qmd]
  post-render: "R/.post-render.R"

title: "logolink: Uma Interface para Execução de Simulações NetLogo a Partir do R"
author: "Daniel Vartanian"
keyword: >
  SIMBRA, NetLogo, R (Programming Language), R Packages, Reproducible Research,
  Agent-Based Modeling, Individual-Based Modeling, Computational Modeling,
  Simulations, Complex Systems, Complexity Science, Generative Science,
  ABM Study Group, University of São Paulo
date: 2026-05-29
date-format: long

website:
  favicon: images/favicon.svg
  site-url: https://danielvartan.github.io/simbra-pres-2/
  repo-url: https://github.com/danielvartan/simbra-pres-2/
  issue-url: https://github.com/danielvartan/simbra-pres-2/issues/
  open-graph:
    image: images/og-image.png
    image-width: 2400
    image-height: 1600
    image-alt: Sustentarea Research and Extension Group
  repo-branch: main

filters:
  - highlight-text

format:
  revealjs:
    open-graph: true
    lang: pt-br
    locale: pt
    language: pt-br
    code-link: true
    code-fold: true
    link-external-newwindow: true
    tbl-cap-location: top
    callout-appearance: simple
    csl: csl/english-apa-author-date.csl
    preview-links: false
    controls: true
    controls-layout: bottom-right
    slide-number: true
    auto-stretch: true
    fig-align: center
    pdf-max-pages-per-slide: 1
    theme: [default, brand, scss/styles.scss]
    title-slide-attributes:
      data-background-color: "#183eff"
    template-partials:
      - html/title-slide.html
    include-in-header: html/include-in-header.html
    menu:
      titleSelector: [h1 h2]
      useTextContentForMissingTitles: false
      hideMissingTitles: false

google-scholar: true
bibliography: references.bib
